/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.rainj.flowlog.domain;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MessageTest {
    // @Test void someLibraryMethodReturnsTrue() {
    //     Library classUnderTest = new Library();
    //     assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    // }
}
